"""empty message

Revision ID: 096c0442f2d5
Revises: 44582444acc5
Create Date: 2022-08-18 09:52:14.730087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096c0442f2d5'
down_revision = '44582444acc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'past_shows')
    op.drop_column('shows', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
