"""empty message

Revision ID: 2c50dc6890d8
Revises: 91fe2c3dbba4
Create Date: 2022-08-19 11:24:12.761541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c50dc6890d8'
down_revision = '91fe2c3dbba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('num_past_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_past_shows')
    op.drop_column('venue', 'num_upcoming_shows')
    # ### end Alembic commands ###
