"""empty message

Revision ID: 7195182cf3ab
Revises: 6c4898ceae7a
Create Date: 2022-08-18 05:44:39.154395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7195182cf3ab'
down_revision = '6c4898ceae7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('Artist_id', sa.Integer(), nullable=False),
    sa.Column('Venue_id', sa.Integer(), nullable=False),
    sa.Column('num_upcoming_shows', sa.Integer(), nullable=True),
    sa.Column('past_shows', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('Artist_id', 'Venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
