"""empty message

Revision ID: 8b5d546c1f19
Revises: 7195182cf3ab
Create Date: 2022-08-18 07:02:02.651636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5d546c1f19'
down_revision = '7195182cf3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('genre')
    # ### end Alembic commands ###
