"""empty message

Revision ID: b3d4f9cc214a
Revises: bdcdf86edd1e
Create Date: 2022-08-18 12:32:56.142900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d4f9cc214a'
down_revision = 'bdcdf86edd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'past_shows')
    op.drop_column('artist', 'past_shows')
    # ### end Alembic commands ###
