"""empty message

Revision ID: bdcdf86edd1e
Revises: 096c0442f2d5
Create Date: 2022-08-18 12:18:33.590471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcdf86edd1e'
down_revision = '096c0442f2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_upcoming_shows')
    op.drop_column('artist', 'num_upcoming_shows')
    # ### end Alembic commands ###
