"""empty message

Revision ID: c54fa33f1a59
Revises: aad55b8e5342
Create Date: 2022-08-19 05:16:32.261848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c54fa33f1a59'
down_revision = 'aad55b8e5342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Start_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_Venue_id_fkey', 'shows', 'venue', ['Venue_id'], ['id'])
    op.create_foreign_key('shows_Artist_id_fkey', 'shows', 'artist', ['Artist_id'], ['id'])
    op.drop_column('shows', 'start_time')
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
