"""empty message

Revision ID: d3775e88ffd8
Revises: 6d4ba38ab25e
Create Date: 2022-08-20 05:33:58.061824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3775e88ffd8'
down_revision = '6d4ba38ab25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('artist', 'num_upcoming_shows')
    op.drop_column('artist', 'num_past_shows')
    op.add_column('venue', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('venue', 'num_upcoming_shows')
    op.drop_column('venue', 'num_past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('num_past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'start_time')
    op.add_column('artist', sa.Column('num_past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'start_time')
    # ### end Alembic commands ###
