"""empty message

Revision ID: e1f9514c6655
Revises: c7d32cf7ab5f
Create Date: 2022-08-18 09:23:04.068116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f9514c6655'
down_revision = 'c7d32cf7ab5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artistgenre', sa.Column('genre_id', sa.String(length=30), nullable=False))
    op.add_column('venuegenre', sa.Column('genre_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venuegenre', 'genre_id')
    op.drop_column('artistgenre', 'genre_id')
    # ### end Alembic commands ###
