"""empty message

Revision ID: e349f516c1aa
Revises: 8b5d546c1f19
Create Date: 2022-08-18 07:19:20.326070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e349f516c1aa'
down_revision = '8b5d546c1f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistgenre',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('venuegenre',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.drop_table('genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genres', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='genre_artist_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', name='genre_pkey')
    )
    op.drop_table('venuegenre')
    op.drop_table('artistgenre')
    # ### end Alembic commands ###
